name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  unit-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Test Image
        run: docker build -f Dockerfile.test -t app-test .

      - name: Run Tests
        run: docker run app-test

  sonarqube:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sonar Scan
        run: echo "Run SonarQube Scan"

  build-image:
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t app:latest .

  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying application"
